### ISSUE TITLE
Problem with masked array

### ISSUE THREAD

**Issue by dopplershift** [Unidata/cftime#60] opened 2018-08-14 16:46 UTC
Not sure what's going on here:
```python
from cftime import num2date
num2date(np.ma.array([0., 1., 2.]), 'hours since 1980-06-03 12:00')
```

gives
```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-56-fbdbe6e3afd0> in <module>()
      3 time_units = 'hours since 1980-06-03 12:00'
      4 
----> 5 num2date(np.ma.array([0., 1., 2.]), time_units)

cftime/_cftime.pyx in cftime._cftime.num2date()

cftime/_cftime.pyx in cftime._cftime.utime.num2date()

~/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py in reshape(a, newshape, order)
    277            [5, 6]])
    278     """
--> 279     return _wrapfunc(a, 'reshape', newshape, order=order)
    280 
    281 

~/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     49 def _wrapfunc(obj, method, *args, **kwds):
     50     try:
---> 51         return getattr(obj, method)(*args, **kwds)
     52 
     53     # An AttributeError occurs if the object does not have

ValueError: cannot reshape array of size 1 into shape (3,)
```

It works if I convert the data to a regular array.

**Comment by jswhit** [comment] 2018-08-14 17:25
This is fixed in master (I think https://github.com/Unidata/cftime/pull/55 fixed it).

**Comment by dopplershift** [comment] 2018-08-14 18:01
Can you or someone put out a release? I'm having code fail just pulling data out of a netCDF file.

**Comment by jswhit** [comment] 2018-08-14 21:10
I can put a source tarball up on PyPi, but don't know how to make binary wheels.

**Comment by jswhit** [comment] 2018-08-14 21:32
We should probably merge at least #62 before creating a new release.

**Comment by jswhit** [comment] 2018-08-15 14:59
I'll make a release today

**Comment by ocefpaf** [comment] 2018-08-15 15:02
> but don't know how to make binary wheels.

Where is the repository that builds the wheels for netcdf4-python? We can probably try to reproduce the logic and/or build both from there.

**Comment by jswhit** [comment] 2018-08-15 15:10
https://github.com/macpython/netcdf4-python-wheels

**Comment by jswhit** [comment] 2018-08-15 15:12
Christoph Gohkle builds windows wheels for netcdf4-python and cftime (https://www.lfd.uci.edu/~gohlke/pythonlibs/), so I will upload his to pypi (I already to this for netcdf4-python since the github repo only builds linux and macos wheels).

**Comment by ocefpaf** [comment] 2018-08-15 15:14
> Christoph Gohkle builds windows wheels for netcdf4-python and cftime (lfd.uci.edu/~gohlke/pythonlibs), so I will upload his to pypi (I already to this for netcdf4-python since the github repo only builds linux and macos wheels).

I guess we could probably use the AppVeyor builds to do that automatically. I'll investigate this in the future.

> macpython/netcdf4-python-wheels

Thanks!

**Comment by ChrisBarker-NOAA** [comment] 2018-08-15 16:41
@ocefpaf: 

those repos in the MacPyton org use multibuild:

https://github.com/matthew-brett/multibuild

Which is kinda a conda-forge light for building both Mac and Linux wheels, (and apparently at least some Windows Wheels), so perhaps it could be used for netCDF4 and Windows wheels.

Reaching out to @matthew-brett and the multi-build project may make sense

**Comment by jswhit** [comment] 2018-08-15 19:42
I was going to upload the source tarball for 1.0.1 (from the release branch), then merge the release branch (pull request #63) and make a tag.  However, it looks like only @jhamman can upload to pypi right now.

**Comment by ChrisBarker-NOAA** [comment] 2018-08-15 21:07
Doesn't it make sense to make a release (tag) here in gitHub first anyway?

**Comment by jswhit** [comment] 2018-08-16 12:11
OK, new release made and files uploaded to pypi. closing now.

**Closed by jswhit** 2018-08-16 12:11 UTC
