### ISSUE TITLE
New 1.1.1.1 pip install errors out on CI

### ISSUE THREAD

**Issue by bsipocz** [Unidata/cftime#161] opened 2020-03-23 23:46 UTC
This is on python3.5 with travis:

https://travis-ci.org/github/astroML/astroML/jobs/666102493#L3490

While release 1.1.1 works as expected, so limiting the version number was a good enough workaround for my usecase for now, but you may want to fix the config files to avoid this issue.

**Comment by jswhit** [comment] 2020-03-24 00:43
Probably a duplicate of https://github.com/Unidata/cftime/issues/154

**Comment by jswhit** [comment] 2020-03-24 02:58
Should be fixed in version 1.1.1.2 release.

**Comment by bsipocz** [comment] 2020-03-24 05:25
The pip install now seems to work, but there are other issues surfacing with numpy:
https://travis-ci.org/github/bsipocz/astroML/jobs/666185062#L4051

So either way, I think I just leave the workaround in there for our CI. Also feel free to close this issue, given that 3.5 is really close to its end of life.

**Comment by jswhit** [comment] 2020-03-24 13:07
Those issues are not cftime related - I think they are due to binary incompatibilities between packages on python 3.5 (due to the fact that the numpy wheels for 3.5 are now rather old).

**Closed by jswhit** 2020-03-24 13:07 UTC

**Comment by bsipocz** [comment] 2020-03-24 16:51
yeah, I think tangentially it's related as everything works fine with the older cftime, but agree that it's not something worth time spending on.
